name: Autonomous Documentation Updates

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug logging'
        required: false
        default: 'false'
        type: boolean

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
          cache-dependency-path: scripts/autonomous-docs/package.json

      - name: Install dependencies
        run: |
          cd scripts/autonomous-docs
          npm ci

      - name: Build TypeScript
        run: |
          cd scripts/autonomous-docs
          npm run build

      - name: Run autonomous documentation system
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd scripts/autonomous-docs
          npm start

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="autodoc/update-$(date +%Y%m%d-%H%M%S)"
          git config --local user.email "action@github.com"
          git config --local user.name "Autonomous Documentation Bot"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "docs: autonomous update" -m "" -m "Generated with Claude Code via Happy" -m "" -m "Co-Authored-By: Claude <noreply@anthropic.com>" -m "Co-Authored-By: Happy <yesreply@happy.engineering>"
          git push -u origin "$BRANCH_NAME"
          gh pr create --title "docs: autonomous documentation update" --body "Automated documentation update from the autonomous docs system." --base main --head "$BRANCH_NAME"

      - name: Upload artifacts (debug)
        if: failure() || inputs.debug == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: autonomous-docs-debug
          path: |
            knowledge-base/audit-trail/
            knowledge-base/changelogs/
            scripts/autonomous-docs/dist/
          retention-days: 7

      - name: Notify on failure
        if: failure()
        run: |
          echo "Autonomous Documentation Update failed"
          echo "Check the logs and debug artifacts for details"
