/**
 * useStartProjectSession — shared "fetch a Power Hour plan and start a
 * focus session" handler. KeepGoingCard (the priority hero) uses this
 * with a pre-fetched plan; mini cards on the home page use it bare to
 * start a session inline without navigating.
 */

import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useFocusStore } from '../stores/useFocusStore'
import { useToast } from '../components/ui/toast'
import { haptic } from '../utils/haptics'

const SESSION_DURATION_MINUTES = 60

type Task = { id: string; text: string }

function tasksFromPlan(plan: any): Task[] {
  if (!plan) return []
  return [
    ...(plan.ignition_tasks || []).map((t: any, i: number) => ({ id: `ign-${i}`, text: t.text })),
    ...(plan.checklist_items || []).map((t: any, i: number) => ({ id: `core-${i}`, text: t.text })),
    ...(plan.shutdown_tasks || []).map((t: any, i: number) => ({ id: `shut-${i}`, text: t.text })),
  ]
}

interface StartOptions {
  /** Plan already fetched by the parent (e.g. KeepGoingCard prefetches one). */
  prefetched?: any
  /** Overrides SESSION_DURATION_MINUTES — e.g. Focus chat passing through a
   *  time budget the user actually stated ("I've got 20 minutes"), so the
   *  plan is sized to right-now instead of a generic default. */
  durationMinutes?: number
}

export function useStartProjectSession(projectId: string | undefined | null) {
  const startSession = useFocusStore(s => s.startSession)
  const navigate = useNavigate()
  const { addToast } = useToast()
  const [loading, setLoading] = useState(false)

  // Returns whether a session actually started — every existing caller
  // fires this and ignores the result (the hook shows its own toast on
  // failure), so this is purely additive. Callers that DO need to know
  // (e.g. a confirm-card deciding whether to show "Done") can await it.
  const start = async ({ prefetched, durationMinutes }: StartOptions = {}): Promise<boolean> => {
    if (!projectId) return false
    haptic.medium()
    setLoading(true)
    try {
      // A prefetched plan was fetched at the default duration — skip it
      // when the caller wants a specific time budget instead, otherwise
      // the session would ignore what the user just said.
      if (prefetched && !durationMinutes) {
        const tasks = tasksFromPlan(prefetched)
        if (tasks.length > 0) {
          startSession(projectId, tasks, prefetched.duration_minutes ?? SESSION_DURATION_MINUTES)
          return true
        }
      }

      const requestedDuration = durationMinutes || SESSION_DURATION_MINUTES
      const res = await fetch(`/api/power-hour?projectId=${projectId}&duration=${requestedDuration}`)
      if (res.status === 429) {
        // The plan was just generated by a sibling request (likely the
        // hero card's prefetch effect) but didn't come back to us in time.
        // Server fix should make this rare, but in case it slips through:
        // open the project so the user isn't dead-ended on the home page.
        addToast({
          title: 'Session still warming up',
          description: 'Opening this project so you can pick a task.',
          action: { label: 'Open project', onClick: () => navigate(`/projects/${projectId}`) },
        })
        navigate(`/projects/${projectId}`)
        return false
      }
      if (!res.ok) {
        if (res.status !== 401) {
          const body = await res.json().catch(() => ({}))
          addToast({
            title: "Couldn't plan session",
            description: body.error || `Power Hour API returned ${res.status}`,
            variant: 'destructive',
            action: { label: 'Open project', onClick: () => navigate(`/projects/${projectId}`) },
          })
        }
        return false
      }
      const data = await res.json()
      const tasks = tasksFromPlan(data.tasks?.[0])
      if (tasks.length === 0) {
        addToast({
          title: "Couldn't plan session",
          description: 'No tasks were generated for this project.',
          variant: 'destructive',
          action: { label: 'Open project', onClick: () => navigate(`/projects/${projectId}`) },
        })
        return false
      }
      startSession(projectId, tasks, data.tasks?.[0]?.duration_minutes ?? requestedDuration)
      return true
    } catch (err) {
      console.error('[useStartProjectSession] failed:', err)
      addToast({
        title: "Couldn't plan session",
        description: err instanceof Error ? err.message : 'Unexpected error',
        variant: 'destructive',
        action: { label: 'Open project', onClick: () => navigate(`/projects/${projectId}`) },
      })
      return false
    } finally {
      setLoading(false)
    }
  }

  return { start, loading }
}
