name: Bundle Size Check

on:
  pull_request:
    branches: [main]
    paths:
      - 'projects/polymath/**'
  push:
    branches: [main]
    paths:
      - 'projects/polymath/**'

jobs:
  bundle-size:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/polymath

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: projects/polymath/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Analyze bundle size
        run: |
          echo "## Bundle Size Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Build Output" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          ls -lh dist/assets/ | awk '{print $9, $5}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Total Size" >> $GITHUB_STEP_SUMMARY
          du -sh dist/ >> $GITHUB_STEP_SUMMARY

      - name: Check bundle size limits
        run: |
          # Get main JS bundle size in KB
          MAIN_SIZE=$(find dist/assets -name 'index-*.js' -exec ls -lk {} \; | awk '{print $5}' | head -1)
          echo "Main bundle size: ${MAIN_SIZE}KB"

          # Fail if main bundle exceeds 200KB
          if [ "$MAIN_SIZE" -gt 200 ]; then
            echo "❌ Main bundle size (${MAIN_SIZE}KB) exceeds limit (200KB)"
            exit 1
          else
            echo "✅ Main bundle size is within limits"
          fi

      - name: Upload bundle stats
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: projects/polymath/dist/
          retention-days: 7
