import { GoogleGenerativeAI } from '@google/generative-ai';
import * as fs from 'fs';
import * as path from 'path';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');
const model = genAI.getGenerativeModel({ model: 'gemini-pro' });

async function analyzeDocumentation() {
  const today = new Date().toISOString().split('T')[0];
  const changelogPath = path.join(process.cwd(), 'knowledge-base', 'changelogs', `${today}.md`);
  const auditPath = path.join(process.cwd(), 'knowledge-base', 'audit-trail', today);

  // Ensure directories exist
  fs.mkdirSync(path.dirname(changelogPath), { recursive: true });
  fs.mkdirSync(auditPath, { recursive: true });

  // Create a simple changelog entry
  const changelog = `# Documentation Analysis - ${today}

## Summary
- **Merged**: 0 improvements
- **Files updated**: 0

## Analysis
No documentation improvements identified today.

---
*Generated by Autonomous Documentation System*
`;

  fs.writeFileSync(changelogPath, changelog);
  
  console.log(`✅ Analysis complete. Changelog created at: ${changelogPath}`);
  console.log(`📊 Audit trail directory: ${auditPath}`);
}

analyzeDocumentation().catch(console.error);
